export const mockProjects = [
  {
    id: 1,
    project_code: "PRJ-2025-0001",
    project_name: "Căn hộ Mỹ Khánh – Phú Mỹ Hưng",
    customer_name: "Nguyễn Văn An",
    customer_phone: "0901234567",
    pm_name: "Trần Thị Bình",
    contract_value: 820_000_000,
    total_paid: 410_000_000,
    total_outstanding_debt: 410_000_000,
    project_status: "under_construction",
    start_date: "2025-02-01",
    expected_end_date: "2025-08-31",
    has_building_permit: true,
    has_material_board: true,
    retention_percent: 5,
    boq_count: 1,
    milestone_count: 4,
    vo_count: 2,
    allocation_count: 3,
    progress_pct: 48,
  },
  {
    id: 2,
    project_code: "PRJ-2025-0002",
    project_name: "Văn phòng Landmark 81 – Tầng 22",
    customer_name: "Công ty TNHH ABC",
    customer_phone: "0287654321",
    pm_name: "Lê Minh Tuấn",
    contract_value: 1_500_000_000,
    total_paid: 300_000_000,
    total_outstanding_debt: 1_200_000_000,
    project_status: "legal_check",
    start_date: "2025-03-15",
    expected_end_date: "2025-12-31",
    has_building_permit: false,
    has_material_board: true,
    retention_percent: 5,
    boq_count: 1,
    milestone_count: 5,
    vo_count: 0,
    allocation_count: 0,
    progress_pct: 5,
  },
  {
    id: 3,
    project_code: "PRJ-2024-0015",
    project_name: "Biệt thự Song Long – Thủ Đức",
    customer_name: "Phạm Thị Hoa",
    customer_phone: "0912345678",
    pm_name: "Trần Thị Bình",
    contract_value: 2_200_000_000,
    total_paid: 2_200_000_000,
    total_outstanding_debt: 0,
    project_status: "completed",
    start_date: "2024-01-10",
    expected_end_date: "2024-11-30",
    has_building_permit: true,
    has_material_board: true,
    retention_percent: 5,
    boq_count: 2,
    milestone_count: 6,
    vo_count: 4,
    allocation_count: 5,
    progress_pct: 100,
  },
]

export const mockBoqLines = [
  { id: 1, project_id: 1, category: "Phần thô", item_name: "Đập tường cũ & xử lý mặt bằng", uom: "m²", qty: 45, cost_price: 180_000, selling_price: 250_000, progress_pct: 100, margin_warning: false },
  { id: 2, project_id: 1, category: "Phần thô", item_name: "Xây tường ngăn mới (gạch nhẹ)", uom: "m²", qty: 32, cost_price: 320_000, selling_price: 420_000, progress_pct: 80, margin_warning: false },
  { id: 3, project_id: 1, category: "Điện – M&E", item_name: "Hệ thống điện âm tường toàn căn", uom: "điểm", qty: 60, cost_price: 450_000, selling_price: 580_000, progress_pct: 60, margin_warning: false },
  { id: 4, project_id: 1, category: "Điện – M&E", item_name: "Thi công điều hòa trung tâm", uom: "bộ", qty: 3, cost_price: 12_500_000, selling_price: 15_800_000, progress_pct: 0, margin_warning: false },
  { id: 5, project_id: 1, category: "Nội thất", item_name: "Tủ bếp gỗ MDF Melamine", uom: "m dài", qty: 5.2, cost_price: 3_800_000, selling_price: 4_200_000, progress_pct: 0, margin_warning: true },
  { id: 6, project_id: 1, category: "Nội thất", item_name: "Sàn gỗ công nghiệp 12mm", uom: "m²", qty: 68, cost_price: 420_000, selling_price: 560_000, progress_pct: 0, margin_warning: false },
  { id: 7, project_id: 1, category: "Hoàn thiện", item_name: "Sơn nước nội thất 2 nước sơn lót", uom: "m²", qty: 180, cost_price: 55_000, selling_price: 78_000, progress_pct: 20, margin_warning: false },
  { id: 8, project_id: 1, category: "Hoàn thiện", item_name: "Ốp gạch toilet (60×60)", uom: "m²", qty: 24, cost_price: 380_000, selling_price: 520_000, progress_pct: 40, margin_warning: false },
  { id: 9, project_id: 1, category: "Hoàn thiện", item_name: "Trần thạch cao phẳng", uom: "m²", qty: 75, cost_price: 210_000, selling_price: 280_000, progress_pct: 30, margin_warning: false },
]

export const mockVOs = [
  {
    id: 1, project_id: 1, vo_code: "VO-2025-001",
    title: "Thêm hệ thống đèn LED âm trần phòng khách",
    status: "customer_pending", customer_status: "pending",
    estimated_cost: 8_500_000, selling_price: 11_200_000,
    selling_price_vat: 12_320_000, vat_rate: "10%",
    request_date: "2025-03-01",
    requested_by: "Lê Văn Cường",
    description: "Khách yêu cầu bổ sung 12 đèn LED âm trần Philips 9W, bao gồm đi dây và công tắc dimmer.",
    guest_link_token: "abc123demo",
  },
  {
    id: 2, project_id: 1, vo_code: "VO-2025-002",
    title: "Thay đổi vật liệu sàn phòng ngủ master",
    status: "director_approved", customer_status: "approved",
    estimated_cost: 14_200_000, selling_price: 18_500_000,
    selling_price_vat: 20_350_000, vat_rate: "10%",
    request_date: "2025-02-20",
    requested_by: "Lê Văn Cường",
    description: "Nâng cấp sàn gỗ từ MDF 12mm lên gỗ tự nhiên Sồi Mỹ 18mm theo yêu cầu của khách hàng.",
    guest_link_token: "def456demo",
  },
]

export const mockMilestones = [
  { id: 1, project_id: 1, milestone_order: 1, milestone_name: "Đặt cọc ký hợp đồng", payment_percent: 20, payment_amount: 164_000_000, paid_amount: 164_000_000, due_date: "2025-02-01", status: "paid" },
  { id: 2, project_id: 1, milestone_order: 2, milestone_name: "Nghiệm thu phần thô", payment_percent: 30, payment_amount: 246_000_000, paid_amount: 246_000_000, due_date: "2025-04-30", status: "paid" },
  { id: 3, project_id: 1, milestone_order: 3, milestone_name: "Nghiệm thu M&E hoàn thiện", payment_percent: 30, payment_amount: 246_000_000, paid_amount: 0, due_date: "2025-07-15", status: "approved" },
  { id: 4, project_id: 1, milestone_order: 4, milestone_name: "Bàn giao & hoàn công", payment_percent: 20, payment_amount: 164_000_000, paid_amount: 0, due_date: "2025-09-30", status: "draft" },
]

export const mockLeads = [
  { id: 1, customer_name: "Hoàng Minh Khoa", phone_number: "0901112233", source: "Facebook", estimated_budget: 650_000_000, pipeline_status: "quoting", assigned_sales: "Nguyễn Thu Hà", is_duplicate_phone: false, created_date: "2025-03-01" },
  { id: 2, customer_name: "Trần Bảo Châu", phone_number: "0912223344", source: "Referral", estimated_budget: 1_200_000_000, pipeline_status: "won", assigned_sales: "Phạm Văn Đức", is_duplicate_phone: false, created_date: "2025-02-15" },
  { id: 3, customer_name: "Lý Thành Long", phone_number: "0923334455", source: "Website", estimated_budget: 450_000_000, pipeline_status: "surveyed", assigned_sales: "Nguyễn Thu Hà", is_duplicate_phone: false, created_date: "2025-03-05" },
  { id: 4, customer_name: "Ngô Bích Trâm", phone_number: "0934445566", source: "TikTok", estimated_budget: 800_000_000, pipeline_status: "new", assigned_sales: "Phạm Văn Đức", is_duplicate_phone: true, created_date: "2025-03-08" },
  { id: 5, customer_name: "Dương Quốc Bảo", phone_number: "0945556677", source: "Zalo", estimated_budget: 2_000_000_000, pipeline_status: "designing", assigned_sales: "Nguyễn Thu Hà", is_duplicate_phone: false, created_date: "2025-02-28" },
]

export const statusLabels: Record<string, string> = {
  draft: "Nháp", legal_check: "Kiểm tra pháp lý",
  under_construction: "Đang thi công", inspecting: "Nghiệm thu",
  completed: "Hoàn thành", warranty: "Bảo hành",
  new: "Mới", surveyed: "Đã khảo sát", designing: "Đang thiết kế",
  quoting: "Đang báo giá", won: "Chốt hợp đồng", lost: "Thất bại",
  pm_review: "PM duyệt", customer_pending: "Chờ KH", customer_approved: "KH đồng ý",
  director_approved: "GĐ duyệt", rejected: "Từ chối",
  paid: "Đã thu", approved: "Đã duyệt", overdue: "Quá hạn",
  pending_approval: "Chờ duyệt",
}

export const fmtVND = (n: number) =>
  new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(n)
